### PR TITLE
Generate type casting

### PR DESCRIPTION
**Pull request by dakerfp**

### CODE REVIEW

**Comment by lpereira** [comment]
Hey Daker -- long time no see.

Thanks for the PR.  Unfortunately, it's not entirely correct.  Type assertions in Go work differently than a static_cast does in C++.  It's closer to what a dynamic_cast does, but the semantics do not translate 1:1.  

There are two forms of type assertions, and even then, things change depending on the type of X.  This section in [Effective Go](https://golang.org/doc/effective_go.html#interface_conversions) explains the details.

In order to implement this, the interface type should be implemented first; here's a [blog post](https://research.swtch.com/interfaces) by Russ Cox about the subject, and explains some of the details of the interface type (some things changed since then) as implemented by Go.

The way I see this implemented is the following: a type registry, similar to what C++ already offers (as RTTI), which we'll most likely disable due to memory-usage concerns.  Luckily, it's trivial to map any type to a unique identifier:

```C++
struct type_registry {
    template <T> static int type_id() { static int id{next_type_id()}; return id; }
private:
    static int next_type_id() { static int id; return ++id; } // ++id to reserve 0 as an empty/invalid type
};
```
With that, it's possible to define functions that work as the first general form (without the "comma ok") thing: `template <T> T type_assert(const moku::interface& iface)`, which will panic if the type_id stored in `iface` differs from `type_registry::type_id<T>()`; and a `template <T> std::tuple<T, bool> try_type_assert(const moku::interface& iface)`, which returns a `<T{nil_value}, false>` if T is of a different type than stored inside iface, and `<T{stored_value}, true>` if it's the correct type.

This is going to work to be needed if X is of type `interface{}`.  It still should be an interface type but could be any type implementing an interface -- so things can, and will, get pretty interesting.  If a type satisfies many different interfaces you should be able to type assert between all of them; Gomoku is already using inheritance for this so this should simplify things a little bit. (In Go even a simple integer can implement an interface, but Gomoku generates a struct for those, so if we need to attach methods, we've got our bases covered.)

Any thoughts?

**Comment by lpereira** [comment]
[Here's a first version](https://gist.github.com/lpereira/fc7774b9ee9cdd324e5feb480ef6918f) of `type_assert` and `try_type_assert`.  It still doesn't work like `dynamic_cast` since we need to build a table of type compatibility.  I still don't know how to do that... maybe a bitmask of type_id?

```C++
template <typename T> int aggregate_types() {
  return 1<<type_registry::type_id<T>();
}

template <typename T1, typename T2, typename... Args> int aggregate_types() {
  return aggregate_types<T1>() | aggregate_types<T2, Args...>();
}
```
And use this to generate the `type_id` field in the `struct interface` type.

This would, however, limit the number of type IDs to just 32, but it illustrates the point, and would make `try_type_assert` work when converting an instance to a one of the interface types it implements.

Do you have any thoughts on this?

**Comment by lpereira** [comment]
Found a simpler way: since the structs are generated anyway, one can simply generate a `is_assertable_to()` template function that takes the type_id (from type_registry) and performs the check. [The example program now compiles](https://gist.github.com/lpereira/b4420046c2c5744d00039504602709d8), but there's UB as the cast needs to go to the original type before going back to the interface types.

**Comment by lpereira** [comment]
Apparently [type erasure can be used to make this work](https://gist.github.com/lpereira/4cd48c663d7a0123d23b5c303aff7dbe)... however, it's quite expensive not only in code size, but also in memory (a pointer for each interface a struct implements, per instance of that struct). That's unsuitable for embedded systems.

**Comment by dakerfp** [comment]
Hi Leandro :-)
Long time!

You're right, I've totally ignored the overall semantics, specially the ", ok" case.
As a target for embedded, isn't wiser to either not allow such costly constructs or simplify them?

I am still digesting your solution. I'll be back later.

**Comment by lpereira** [comment]
It's hard to implement something like the `Print` family of functions from the `fmt` package without empty interfaces and a kind of type assertion that won't panic if it's not of the right type. So I'm not sure if this can be left out from an embedded system.  I'm fine with something that's not optimal but works -- and can be optimized in the future, though.

**Comment by dakerfp** [comment]
Early adopting C++20 concepts isn't a solution either?

**Comment by lpereira** [comment]
The type-erasure thing is essentially what concepts are, right? The issue is compiler support; I'd like to use at most C++14, mostly because of this issue.  In any case, yeah, concepts could be used in the future when SDKs for the embedded targets have caught up with the language.

**Comment by lpereira** [comment]
BTW, the version using type erasure doesn't work as well if the struct derives from more than one struct. Back to the drawing board, I guess.

**Comment by dakerfp** [comment]
Isn't possible for each type hold the list of interfaces they accept, and statically create the type cast functions whenever used like a go_cast<MyClass, Interface>(ptr)?

**Comment by dakerfp** [comment]
`#include <string>
#include <tuple>

// interface
struct VoidInterface {
	virtual void Void() = 0;
};

// interface
struct Stringer : virtual public VoidInterface {
	virtual std::string String() = 0;
	void Void() {}
};

// interface
struct Err : virtual public VoidInterface {
	virtual std::string Error() = 0;
	void Void() {}
};

template<typename I, typename T>
std::tuple<T*, bool> go_cast(I *t) {
	auto ptr = dynamic_cast<T*>(t);
	return std::make_tuple(ptr, ptr!=nullptr);
}

struct MyString : virtual public VoidInterface, Stringer, Err {
	void Void() {}

	std::string String() {
		return "ma oe";
	}

	std::string Error() {
		return "bad boy";
	}
};

#include <iostream>

int main() {
	MyString mc{};
	Stringer *s(&mc);
	Err *e(&mc);

	auto tp = go_cast<Stringer, MyString>(s);
	std::cout << std::get<0>(tp)->Error() << std::endl;

	auto tp2 = go_cast<Err, MyString>(e);
	std::cout << std::get<0>(tp2)->String() << std::endl;

	VoidInterface* ifc = &mc;

	auto tp3 = go_cast<VoidInterface, Stringer>(ifc);
	std::cout << std::get<0>(tp3)->String() << std::endl;

	auto tp4 = go_cast<VoidInterface, Err>(ifc);
	std::cout << std::get<0>(tp4)->Error() << std::endl;

	return 0;
}`

**Comment by dakerfp** [comment]
```c++
#include <string>
#include <tuple>

// interface
struct VoidInterface {
	virtual void Void() = 0;
};

// interface
struct Stringer : virtual public VoidInterface {
	virtual std::string String() = 0;
	void Void() {}
};

// interface
struct Err : virtual public VoidInterface {
	virtual std::string Error() = 0;
	void Void() {}
};

template<typename I, typename T>
std::tuple<T*, bool> go_cast(I *t) {
	auto ptr = dynamic_cast<T*>(t);
	return std::make_tuple(ptr, ptr!=nullptr);
}

struct MyString : virtual public VoidInterface, Stringer, Err {
	void Void() {}

	std::string String() {
		return "ma oe";
	}

	std::string Error() {
		return "bad boy";
	}
};

#include <iostream>

int main() {
	MyString mc{};
	Stringer *s(&mc);
	Err *e(&mc);

	auto tp = go_cast<Stringer, MyString>(s);
	std::cout << std::get<0>(tp)->Error() << std::endl;

	auto tp2 = go_cast<Err, MyString>(e);
	std::cout << std::get<0>(tp2)->String() << std::endl;

	VoidInterface* ifc = &mc;

	auto tp3 = go_cast<VoidInterface, Stringer>(ifc);
	std::cout << std::get<0>(tp3)->String() << std::endl;

	auto tp4 = go_cast<VoidInterface, Err>(ifc);
	std::cout << std::get<0>(tp4)->Error() << std::endl;

	return 0;
}
```

**Comment by lpereira** [comment]
That's a simple solution -- however, it uses dynamic casting, which requires [RTTI](https://en.wikipedia.org/wiki/Run-time_type_information).  This has some code size implications.  I'd like to avoid it as much as possible -- in fact, I'd like code to be built with `-fno-exceptions -fno-rtti`. There must be a way around this; I just don't know what it is yet.

**Comment by dakerfp** [comment]
Could we define each interface as following? because go interfaces are usually small:

```c++
struct Stringer {
    int type_id;
    void *value;
    std::function<std::string()> _String(void *)

    std::string String() {
        return _String(value);
    }
    template<typename T>
    tuple<T*, bool> cast() {
        // ... use Stringer::type_id to check if it is possible
    }; 

    template<typename T>
    static Stringer make_interface(T* v) {
         return Stringer {
             T::type_id,
             v,
             T::String // do a proper cast
         };
    }
};

struct MyStruct {
   static int type_id = static_get_type_id;
    std::string String() { return "ma oe"; }  
};
```

**Comment by lpereira** [comment]
Found a way [that's a lot simpler](https://gist.github.com/lpereira/4c12606aeabc03feabd63749fd26ddfa); please take a look.  It's one of those things that seems obvious in retrospect. :)

So, in the end, your PR is good for merging; I'd just like to ask two changes:

- change `static_assert` to `moku::type_assert`
- if it's a "comma, ok" kind of deal, change that call to `moku::try_type_assert` (and remember that `try_type_assert` will return a `std::tuple`); don't worry about the `_` variable just yet.

**Comment by lpereira** [comment]
Merged with changes, thanks!

**Pull request closed without merging**
